spring:
  application:
    name: trades

  main:
    web-application-type: servlet

  web:
    resources:
      cache:
        period: P365D
      chain:
        cache: true
        gzipped: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  margin:
    leverage: 4

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  forward-headers-strategy: framework
  tomcat:
    shutdown-port: -1
    threads:
      max: 50
      min-spare: 5
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
    context-path: /
    jsp:
      init-parameters:
        development: false
        checkInterval: 0
        mappedfile: false
        trimSpaces: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/json,application/javascript
    min-response-size: 1024

features:
  swagger:
    enabled: false

springdoc:
  api-docs:
    enabled: ${features.swagger.enabled}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${features.swagger.enabled}
    path: /swagger-ui.html
    url: /v3/api-docs
  webmvc:
    enabled: ${features.swagger.enabled}
